highlighter: rouge
ga: "UA-109631523-1"
gems:
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      last_modified_at: "2017-03-13"
